FROM microsoft/dotnet

MAINTAINER Thang Chung "thangchung@ymail.com"

# Set environment variables
ENV ASPNETCORE_SERVER.URLS="http://*:6000"
ENV ASPNETCORE_ENVIRONMENT="Development"

# Copy files to app directory
COPY . /app

# Set working directory
WORKDIR /app/src/Services/Sample/Cik.Services.Sample.SampleService

# Restore NuGet packages
RUN ["dotnet", "restore", "--configfile", "/app/NuGet.config"]

# Open up port
EXPOSE 6000

# Run the app
ENTRYPOINT ["dotnet", "run"]